apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-docker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-docker-app
  template:
    metadata:
      labels:
        app: my-docker-app
    spec:
      containers:
      - name: my-docker-app
        image: bhargavram458/my-docker-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-docker-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-docker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
